name: sbqops
channels:
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.14=h5eee18b_0
  - binutils=2.44=hc03a8fd_2
  - binutils_impl_linux-64=2.44=h4b9a079_2
  - binutils_linux-64=2.44=hc03a8fd_2
  - bzip2=1.0.8=h5eee18b_6
  - c-compiler=1.11.0=h9722593_0
  - ca-certificates=2025.12.2=h06a4308_0
  - cuda-cccl_linux-64=13.1.115=h06a4308_0
  - cuda-command-line-tools=13.1.1=h06a4308_0
  - cuda-compiler=13.1.1=h43f7919_0
  - cuda-crt-dev_linux-64=13.1.115=h06a4308_0
  - cuda-crt-tools=13.1.115=h06a4308_0
  - cuda-ctadvisor=13.1.115=h7354ed3_0
  - cuda-cudart=13.1.80=h7354ed3_0
  - cuda-cudart-dev=13.1.80=h7354ed3_0
  - cuda-cudart-dev_linux-64=13.1.80=hfb20e49_0
  - cuda-cudart-static=13.1.80=h7354ed3_0
  - cuda-cudart-static_linux-64=13.1.80=hfb20e49_0
  - cuda-cudart_linux-64=13.1.80=hfb20e49_0
  - cuda-cuobjdump=13.1.115=h80a0ff4_0
  - cuda-cupti=13.1.115=h7354ed3_0
  - cuda-cupti-dev=13.1.115=h7354ed3_0
  - cuda-cuxxfilt=13.1.115=h80a0ff4_0
  - cuda-documentation=12.4.127=0
  - cuda-driver-dev=13.1.80=h7354ed3_0
  - cuda-driver-dev_linux-64=13.1.80=hfb20e49_0
  - cuda-gdb=13.1.115=h0c1f0ea_0
  - cuda-libraries=13.1.1=h06a4308_0
  - cuda-libraries-dev=13.1.1=h06a4308_0
  - cuda-nsight=13.1.115=h6061065_0
  - cuda-nvcc=13.1.115=h02f8991_0
  - cuda-nvcc-dev_linux-64=13.1.115=he2511ca_0
  - cuda-nvcc-impl=13.1.115=hfb20e49_0
  - cuda-nvcc-tools=13.1.115=h7354ed3_0
  - cuda-nvcc_linux-64=13.1.115=h8a62f36_0
  - cuda-nvdisasm=13.1.115=h80a0ff4_0
  - cuda-nvml-dev=13.1.115=h80a0ff4_0
  - cuda-nvprune=13.1.115=h80a0ff4_0
  - cuda-nvrtc=13.1.115=h7354ed3_0
  - cuda-nvrtc-dev=13.1.115=h7354ed3_0
  - cuda-nvtx=13.1.115=h7354ed3_0
  - cuda-nvvm-dev_linux-64=13.1.115=h06a4308_0
  - cuda-nvvm-impl=13.1.115=h47b2149_0
  - cuda-nvvm-tools=13.1.115=h47b2149_0
  - cuda-opencl=13.1.115=h6334c1c_0
  - cuda-opencl-dev=13.1.115=h7354ed3_0
  - cuda-profiler-api=13.1.115=h6061065_0
  - cuda-sanitizer-api=13.1.118=h80a0ff4_0
  - cuda-tileiras=13.1.80=h7354ed3_0
  - cuda-toolkit=11.8.0=0
  - cuda-tools=13.1.1=h06a4308_0
  - cuda-version=13.1=he7c9b7b_3
  - cuda-visual-tools=13.1.1=h06a4308_0
  - cxx-compiler=1.11.0=h2a195f4_0
  - dbus=1.16.2=h5bd4931_0
  - expat=2.7.3=h7354ed3_4
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.14.1=hf5b9546_0
  - gcc_impl_linux-64=14.3.0=h4943218_4
  - gcc_linux-64=14.3.0=hda73cce_12
  - gds-tools=1.16.1.26=h48ee5e2_0
  - gmp=6.3.0=h6a678d5_0
  - gxx_impl_linux-64=14.3.0=he634eba_4
  - gxx_linux-64=14.3.0=hca8765c_12
  - icu=73.1=h6a678d5_0
  - kernel-headers_linux-64=4.18.0=h3108a97_1
  - ld_impl_linux-64=2.44=h153f514_2
  - libcublas=13.2.1.1=he43fd09_0
  - libcublas-dev=13.2.1.1=h7354ed3_0
  - libcufft=12.1.0.78=h7354ed3_0
  - libcufft-dev=12.1.0.78=h7354ed3_0
  - libcufile=1.16.1.26=h1ffec3f_0
  - libcufile-dev=1.16.1.26=h7354ed3_0
  - libcurand=10.4.1.81=h7354ed3_0
  - libcurand-dev=10.4.1.81=h7354ed3_0
  - libcusolver=12.0.9.81=h13f4c66_0
  - libcusolver-dev=12.0.9.81=h7354ed3_0
  - libcusparse=12.7.3.1=h41c5c2b_0
  - libcusparse-dev=12.7.3.1=h41c5c2b_0
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=14.3.0=he7458c1_104
  - libgcc-ng=15.2.0=h166f726_7
  - libglib=2.86.3=h8b17d9a_0
  - libglvnd=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libnl=3.11.0=hb25bd0a_0
  - libnpp=13.0.3.3=h7354ed3_0
  - libnpp-dev=13.0.3.3=h7354ed3_0
  - libnsl=2.0.0=h5eee18b_0
  - libnuma=2.0.19=hee96239_0
  - libnvfatbin=13.1.115=h7354ed3_0
  - libnvfatbin-dev=13.1.115=h7354ed3_0
  - libnvjitlink=13.1.115=h7354ed3_0
  - libnvjitlink-dev=13.1.115=h7354ed3_0
  - libnvjpeg=13.0.3.75=h7354ed3_0
  - libnvjpeg-dev=13.0.3.75=h06a4308_0
  - libnvptxcompiler-dev=13.1.115=h06a4308_0
  - libnvptxcompiler-dev_linux-64=13.1.115=h06a4308_0
  - libopengl=1.7.0=h5eee18b_2
  - libpng=1.6.54=hee55ce4_0
  - libsanitizer=14.3.0=hd4faa28_4
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-devel_linux-64=14.3.0=he7458c1_104
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxkbfile=1.1.0=hf54ef8a_2
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - nsight-compute=2025.4.1.2=h6fab40e_0
  - nspr=4.37=h8459abe_0
  - nss=3.117=h3135ca0_0
  - ocl-icd=2.3.3=h47b2149_0
  - opencl-headers=2025.07.22=hfb20e49_0
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=py312h06a4308_1
  - pcre2=10.46=hf426167_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.12=hd17a9e1_1
  - rdma-core=60.0=h7354ed3_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.10.1=py312h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - sysroot_linux-64=2.28=h3108a97_1
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025c=he532380_0
  - wayland=1.24.0=hdac8c69_0
  - wheel=0.46.3=py312h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h382ed1a_1
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=h9b100fa_2
  - xorg-libxdamage=1.1.6=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxi=1.8.2=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxtst=1.2.5=h9b100fa_3
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - annotated-types==0.7.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - cryptography==46.0.4
      - cudensitymat-cu12==0.4.0
      - cupauliprop-cu12==0.2.0
      - cuquantum-cu11==24.8.0
      - cuquantum-cu12==26.1.0
      - custabilizer-cu12==0.2.0
      - custatevec-cu11==1.6.0.post1
      - custatevec-cu12==1.12.0
      - cutensor-cu11==2.2.0
      - cutensor-cu12==2.4.1
      - cutensornet-cu11==2.5.0
      - cutensornet-cu12==2.11.0
      - cycler==0.12.1
      - cython==3.2.4
      - dill==0.4.1
      - fonttools==4.61.1
      - ibm-cloud-sdk-core==3.24.2
      - ibm-platform-services==0.73.1
      - idna==3.11
      - kiwisolver==1.4.9
      - matplotlib==3.10.8
      - mealpy==3.0.3
      - mthree==3.0.0
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-nvjitlink-cu12==12.9.86
      - opfunu==1.0.1
      - orjson==3.11.5
      - pandas==3.0.0
      - pillow==12.1.0
      - psutil==7.2.1
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyjwt==2.10.1
      - pyparsing==3.3.2
      - pyspnego==0.12.0
      - python-dateutil==2.9.0.post0
      - qiskit==2.1.1
      - qiskit-aer-gpu==0.15.1
      - qiskit-aer-gpu-cu11==0.17.2
      - qiskit-ibm-runtime==0.45.0
      - requests==2.32.5
      - requests-ntlm==1.3.0
      - runningman==2.3.0
      - rustworkx==0.17.1
      - scipy==1.16.3
      - seaborn==0.13.2
      - six==1.17.0
      - stevedore==5.6.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.3
